version: '3'

services:
  wpbit_php:
    build: ./php
    container_name: notebook_php
    volumes:
      - ../server:/var/www/html
    ports:
      - 8181:80
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public_html
      WEB_DOCUMENT_INDEX: index.php
      PHP_MEMORY_LIMIT: 2G
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_POST_MAX_SIZE: 512M
      PHP_DISPLAY_ERRORS: 1
      php.xdebug.max_nesting_level: 500
    depends_on:
      - notebook_mysql


  notebook_mysql:
    build: ./mysql/
    container_name: notebook_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notebook_mysql
    ports:
      - 3131:3306
    volumes:
      - notebook-db:/var/lib/mysql
volumes:
  notebook-db:
